<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Zeeshan" ignored="0" name="FREE CRM Test" tests="1" failures="1" timestamp="18 Apr 2020 09:54:47 GMT" time="75.538" errors="0">
  <testcase name="feature" time="74.225" classname="com.qa.Runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	expected [16] but found [15]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
expected [16] but found [15]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at com.qa.Runner.TestRunner.feature(TestRunner.java:36)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: The following asserts failed:
expected [16] but found [15]
at com.qa.stepDefinations.StepDefination.Close_the_Browser(StepDefination.java:71)
at âœ½.Then Close the Browser(E:/OxygenEclipse/CucumberPageObjectmodel/src/main/java/com/qa/features/validatehomepage.feature:22)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- FREE CRM Test -->
